### PR TITLE
Fixed a pile of bogus types, which prevented even very basic use of Tao.Freetype on 64bit Linux.

### PR DESCRIPTION
**Pull request by chrisforbes**
Well aware this isn't going to work on LLP64 platforms -- some trickery is required.

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Done.   I do not quite like the change, as you point out, it will break on LLP64, but perhaps FreeType is not used there.

**Comment by chrisforbes** [comment]
@migueldeicaza: Would you like me to put together a followup patch that works (via magic, will have to be) on both LP64 and LLP64, and ideally fixes _all_ of Tao.FreeType, not just the bare essentials?

**Comment by chrisforbes** [comment]
@migueldeicaza: Ideal would be for FreeType upstream to use fixed-size types, of course. Not much point in advertising a fixedpoint type as 26.6 when it's actually 58.6 on half the systems it's used on.

**Comment by migueldeicaza** [comment]
I would love to.

**Comment by chrisforbes** [comment]
What is the roadmap for Tao? It seems pretty dead :(

**Pull request merged**
